projectBaoVic/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['namespace' => 'FrontEnd'], function(){
    Route::get('homepage','HomepageController@index')->name('homeA');
    Route::get('blog','BlogController@list')->name('viewBlog');
    Route::get('blog/{id}','BlogController@detail')->name('detailBlog');
    Route::post('rate','RateController@rate')->name('rateBlog');
    Route::post('comment','BlogController@comment')->name('commentBlog');
    Route::resource('product','ProductController');
   
    Route::group(['namespace' => 'User','prefix'=>'member'], function(){
        Route::get('login','MemberController@getLogin')->name('viewLogin');
        Route::post('login','MemberController@login')->name('login');
        Route::get('register','MemberController@getRegister')->name('viewRegister');
        Route::post('register','MemberController@register')->name('register');
        Route::get('logout','MemberController@logout')->name('logout');
        Route::get('account','MemberController@getAccount')->name('viewAccount');
        Route::post('account','MemberController@update');
    });
});

// Route::get('father',function(){
//     return view('frontend.layout.father');
// });


Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::group(['namespace' => 'Admin','prefix'=>'admin'], function(){
    Route::get('dashboard','HomeController@index');
    Route::get('profile','UserController@index')->name('show');
    // Route::post('edit/{id}','UserController@update');
    Route::post('profile','UserController@update');
    Route::resource('country', 'CountryController');
    Route::resource('blog', 'BlogController');
    Route::resource('brand','BrandController');
    Route::resource('category','CategoryController');
});

projectBaoVic/app/Http/Controllers/FrontEnd/BlogController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Blog;
use App\Rate;
use App\Comment;
use App\User;
use Auth;

class BlogController extends Controller
{
    public function list(){
        // $blog = Blog::orderBy('created_at', 'desc')->paginate(3);
        $blog = Blog::latest()->paginate(3);
        // dd($blog);
        return view('frontend.blog.list',compact('blog'));
    }

    public function detail($id){
        $blog = Blog::findorfail($id);
        $previous = Blog::where('id', '<', $blog->id)->max('id');
        $next = Blog::where('id', '>', $blog->id)->min('id');
        $rate = Rate::where('blog_id',$blog->id)->count();
        $sumStar = Rate::where('blog_id',$blog->id)->sum('star');
        $comment = Comment::where('blog_id',$blog->id)->where('parent_id',NULL)->get();
        $commentNotNull = Comment::where([
            ['blog_id', '=', $blog->id],
            ['parent_id', '!=', NULL]
        ])->get();
        // dd($comment['0']->user_id);
        // dd($commentNotNull);
        $lamTron = 0;

        if($rate > 0){
            $lamTron = round($sumStar/$rate);
        }

        return view('frontend.blog.detail',compact('blog','previous','next','lamTron','comment','commentNotNull'));

    }

    public function comment(Request $request){
        $data = $request->all();
        $insert = Comment::create($data);
        return redirect()->back();
        // dd($insert);
    }
}

projectBaoVic/app/Http/Controllers/FrontEnd/HomepageController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomepageController extends Controller
{
    public function index(){
        return view('frontend.homepage');
    }
}

projectBaoVic/app/Http/Controllers/FrontEnd/ProductController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\Product;

class ProductController extends Controller
{
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::check()){
            $products = Product::all();
            return view('frontend.product.all',compact('products'));
        }else{
            return redirect()->route('viewLogin');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

projectBaoVic/app/Http/Controllers/FrontEnd/RateController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\Rate;

class RateController extends Controller
{
    public function rate(Request $request){
        $rate = Rate::create([
            'user_id' => $request->userId,
            'blog_id' => $request->blogId,
            'star' => $request->Values,
        ]);
        // dd($rate);
    }


}

projectBaoVic/app/Http/Controllers/FrontEnd/User/MemberController.php
<?php

namespace App\Http\Controllers\FrontEnd\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\Country;
use App\Http\Requests\BackEnd\UserRequest;
use App\User;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\FrontEnd\LoginRequest;


class MemberController extends Controller
{
    public function getLogin(){
        return view('frontend.login');
    }

    public function login(LoginRequest $request){
        $credentials = [
            'email' => $request->email,
            'password' => $request->password,
            'level' => 0
        ];
        
        $remember = false;
        
        if($request->remember_token){
            // dd($request->remember_token);
            $remember = true;
        }

        if(Auth::attempt($credentials,$remember)){
            // dd($remember);
            return redirect()->route('homeA');
        }else{
            // dd($remember);
            // dd(Auth::attempt($credentials,$remember));
            return redirect()->back()->with('error','Sai tk or mk');
        }
    }

    public function getRegister(){
        $data = Country::all();
        return view('frontend.register',compact('data'));
    }

    public function register(UserRequest $request){
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->level = 0;
        $user->password = Hash::make($request->password);
        $user->phone = $request->phone;
        $user->country = $request->country;
        $user->message = $request->message;
        $img = $request->image;
        if($img){
            $getNameImg = $img->getClientOriginalName();
            $user->image = $getNameImg;
        }
        $user->save();
        if($user->save()){
            if($img != null){
                $img->move('upload/customer',$getNameImg);
            }
            return redirect()->route('viewLogin')->with('message','DK t.cong');
        }else{
            return redirect()->route('viewLogin')->with('error','DK t.bai');
        }
    }

    public function logout(){
        Auth::logout();
        return redirect()->route('viewLogin'); 
    }

    public function getAccount(){
        if(Auth::check()){
            $data = Country::all();
            return view('frontend.account.account',compact('data'));
        }else{
            return redirect()->route('viewLogin');
        }
        
    }

    public function update(UserRequest $request){
        $id = Auth::id();
        $user = User::findorfail($id);
        $img = $request->image;
        $data = $request->all();
        if($img){
            $getNameImg = $img->getClientOriginalName();
            $data['image'] = $getNameImg;
        }

        if($data['password']){
            $data['password'] = Hash::make($data['password']);
        }else{
            $data['password'] = $user->password;
        }

        $update = $user->update($data);
        if($update){
            if($img != null){
                $img->move('upload/customer',$getNameImg);
            }
            return redirect()->route('viewAccount')->with('message','Cap nhat t.cong');
        }else{
            return redirect()->route('viewAccount')->with('error','Cap nhat t.bai');
        }
    }

}

projectBaoVic/resources/views/frontend/layout/father.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
    <link href="{{asset('FE/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('FE/css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{asset('FE/css/prettyPhoto.css')}}" rel="stylesheet">
    <link href="{{asset('FE/css/price-range.css')}}" rel="stylesheet">
    <link href="{{asset('FE/css/animate.css')}}" rel="stylesheet">
	<link href="{{asset('FE/css/main.css')}}" rel="stylesheet">
	<link href="{{asset('FE/css/responsive.css')}}" rel="stylesheet">      
    <link rel="shortcut icon" href="{{asset('FE/images/ico/favicon.ico')}}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{asset('FE/images/ico/apple-touch-icon-144-precomposed.png')}}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{asset('FE/images/ico/apple-touch-icon-114-precomposed.png')}}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{asset('FE/images/ico/apple-touch-icon-72-precomposed.png')}}">
    <link rel="apple-touch-icon-precomposed" href="{{asset('FE/images/ico/apple-touch-icon-57-precomposed.png')}}">
    <link type="text/css" rel="stylesheet" href="{{asset('FE/css/rate.css')}}">
	<meta name="csrf-token" content="{{ csrf_token() }}" />
</head><!--/head-->

<body>
	@include('frontend.layout.header')

	@php 
		$url = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
		$convertUrl = explode('/',(parse_url($url, PHP_URL_PATH)));
		// echo "<pre/>";
		// var_dump($convertUrl);
		if(empty($convertUrl[5])){
			$getNameView = $convertUrl[4];
		}else{
			$getNameView = $convertUrl[5];
		}
		// var_dump($getNameView);
	@endphp

	@if(($getNameView == 'homepage'))
	@include('frontend.layout.slider')
		<section id=@yield('id')>
			<div class="container">
				<div class="row">
					@include('frontend.layout.menuForCategory')
					@yield('content')
				</div>
			</div>
		</section>
	@endif

	@if(($getNameView == 'account') || ($getNameView == 'product'))
		<section id=@yield('id')>
			<div class="container">
				<div class="row">
					@include('frontend.layout.menuForMember')
					@yield('content')
				</div>
			</div>
		</section>
	@endif

	@if(($getNameView == 'login') || ($getNameView == 'cart') || ($getNameView == 'register'))
		<section id=@yield('id')>
			<div class="container">
				<div class="row">
					@yield('content')
				</div>
			</div>
		</section>
	@endif

	@if(($getNameView == 'blog'))
		<section id=@yield('id')>
			<div class="container">
				<div class="row">
					@include('frontend.layout.menuForCategory')
					@yield('content')
				</div>
			</div>
		</section>
	@endif

    @include('frontend.layout.footer')
	
    <script src="{{asset('FE/js/jquery.js')}}"></script>
	<script src="{{asset('FE/js/bootstrap.min.js')}}"></script>
	<script src="{{asset('FE/js/jquery.scrollUp.min.js')}}"></script>
	<script src="{{asset('FE/js/price-range.js')}}"></script>
    <script src="{{asset('FE/js/jquery.prettyPhoto.js')}}"></script>
    <script src="{{asset('FE/js/main.js')}}"></script>
    <script src="{{asset('FE/js/jquery-1.9.1.min.js')}}"></script>
    <script>
        if(screen.width <= 736){
            document.getElementById("viewport").setAttribute("content", "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no");
        }
    </script>
        <script>
			$(document).ready(function(){
				//vote
				$('.ratings_stars').hover(
					// Handles the mouseover
					function() {
						$(this).prevAll().andSelf().addClass('ratings_hover');
						// $(this).nextAll().removeClass('ratings_vote'); 
					},
					function() {
						$(this).prevAll().andSelf().removeClass('ratings_hover');
						// set_votes($(this).parent());
					}
				);
				
				//Rate
				$('.ratings_stars').click(function(){
					var Values =  $(this).find("input").val();
					loggedIn = "{{ Auth::check() }}";
					blogId = $("#blog_id").val();
					token = $('input[name="_token"]').val();

					if(loggedIn == ''){
						alert('Vui long dang nhap');
					}else{
						userId = "{{ Auth::id() }}";
						// console.log(userId);

						$.ajaxSetup({
							headers: {
								'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
							}
                    	});
					
						$.ajax({
							method: "POST",
							url: '{{route('rateBlog')}}',
							data: {
								token, blogId, userId, Values
							}
							
						});
					}
			
					// alert(Values);
					if ($(this).hasClass('ratings_over')) {
						$('.ratings_stars').removeClass('ratings_over');
						$(this).prevAll().andSelf().addClass('ratings_over');
					} else {
						$(this).prevAll().andSelf().addClass('ratings_over');
					}
					// e.preventDefault();
				});

				//Cmt
				$('.btnCmt').click(function(e){
					loggedIn = "{{ Auth::check() }}";

					if(loggedIn == ''){
						alert('Vui long dang nhap');
						e.preventDefault();
					}else{
						if(!$(".comment").val()){
							alert('Nhap binh luan');
							e.preventDefault();
						}else{
							$('.btnCmt').submit();
						}
					}
				});

				//Replay
				$('.btnReplay').click(function(){
					id = $(this).closest(".cmt123").find(".idCmtFather").val();
					$(".parent_id").val(id);
					// console.log(id);
				});

			});
		</script>
</body>
</html>

projectBaoVic/resources/views/frontend/layout/footer.blade.php
<footer id="footer"><!--Footer-->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="companyinfo">
                        <h2><span>e</span>-shopper</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="{{asset('FE/images/home/iframe1.png')}}" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                    
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="{{asset('FE/images/home/iframe2.png')}}" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                    
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="{{asset('FE/images/home/iframe3.png')}}" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                    
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="{{asset('FE/images/home/iframe4.png')}}" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="{{asset('FE/images/home/map.png')}}" alt="" />
                        <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Service</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Online Help</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Change Location</a></li>
                            <li><a href="#">FAQ’s</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Quock Shop</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">T-Shirt</a></li>
                            <li><a href="#">Mens</a></li>
                            <li><a href="#">Womens</a></li>
                            <li><a href="#">Gift Cards</a></li>
                            <li><a href="#">Shoes</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Policies</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Privecy Policy</a></li>
                            <li><a href="#">Refund Policy</a></li>
                            <li><a href="#">Billing System</a></li>
                            <li><a href="#">Ticket System</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Company Information</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Store Location</a></li>
                            <li><a href="#">Affillate Program</a></li>
                            <li><a href="#">Copyright</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 col-sm-offset-1">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <form action="#" class="searchform">
                            <input type="text" placeholder="Your email address" />
                            <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                            <p>Get the most recent updates from <br />our site and be updated your self...</p>
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
                <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
            </div>
        </div>
    </div>
    
</footer><!--/Footer-->

projectBaoVic/resources/views/frontend/layout/header.blade.php
<header id="header"><!--header-->
    <div class="header_top"><!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->
    
    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-md-4 clearfix">
                    <div class="logo pull-left">
                        <a href="{{route('homeA')}}"><img src="{{asset('FE/images/home/logo.png')}}" alt="" /></a>
                    </div>
                    <div class="btn-group pull-right clearfix">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                USA
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="">Canada</a></li>
                                <li><a href="">UK</a></li>
                            </ul>
                        </div>
                        
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                DOLLAR
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="">Canadian Dollar</a></li>
                                <li><a href="">Pound</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-8 clearfix">
                    <div class="shop-menu clearfix pull-right">
                        <ul class="nav navbar-nav">
                            @if (Auth::check())
                                <li>
                                    <a href="{{route('viewAccount')}}"><i class="fa fa-user"></i> Account</a>
                                </li>
                            @endif
                            <li><a href=""><i class="fa fa-star"></i> Wishlist</a></li>
                            <li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
                            <li><a href="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>
                            @if (Auth::check())
                                <li>
                                    <a href="{{(URL('member/logout'))}}"><i class="fa fa-lock"></i> Logout</a>
                                </li>
                            @else
                                <li><a href="{{(route('viewLogin'))}}"><i class="fa fa-lock"></i> Login</a></li>
                                <li><a href="{{(route('viewRegister'))}}"><i class="fa fa-lock"></i> Register</a></li>
                            @endif
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a href="{{route('homeA')}}" class="active">Home</a></li>
                            <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="shop.html">Products</a></li>
                                    <li><a href="product-details.html">Product Details</a></li> 
                                    <li><a href="checkout.html">Checkout</a></li> 
                                    <li><a href="cart.html">Cart</a></li> 
                                    <li><a href="login.html">Login</a></li> 
                                </ul>
                            </li> 
                            <li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="{{route('viewBlog')}}">Blog List</a></li>
                                    <li><a href="blog-single.html">Blog Single</a></li>
                                </ul>
                            </li> 
                            <li><a href="404.html">404</a></li>
                            <li><a href="contact-us.html">Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search"/>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

projectBaoVic/resources/views/frontend/layout/menuForMember.blade.php
<div class="col-sm-3" id="a3">
    <div class="left-sidebar">
        <h2>Account</h2>
        <div class="panel-group category-products" id="accordian">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="{{route('viewAccount')}}">
                            <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                            Account
                        </a>
                    </h4>
                </div>
                {{-- <div id="sportswear" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
                            <li><a href="#">Nike </a></li>
                            <li><a href="#">Under Armour </a></li>
                            <li><a href="#">Adidas </a></li>
                            <li><a href="#">Puma</a></li>
                            <li><a href="#">ASICS </a></li>
                        </ul>
                    </div>
                </div> --}}
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="{{route('product.index')}}">
                            <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                            My Product
                        </a>
                    </h4>
                </div>
            </div> 
        </div>
    </div>
</div>