projectBaoVic/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['namespace' => 'FrontEnd'], function(){
    Route::get('homepage','HomepageController@index')->name('homeA');
    Route::get('blog','BlogController@list')->name('viewBlog');
    Route::get('blog/{id}','BlogController@detail')->name('detailBlog');
    Route::post('rate','RateController@rate')->name('rateBlog');
    Route::post('comment','BlogController@comment')->name('commentBlog');
    Route::resource('product','ProductController');
   
    Route::group(['namespace' => 'User','prefix'=>'member'], function(){
        Route::get('login','MemberController@getLogin')->name('viewLogin');
        Route::post('login','MemberController@login')->name('login');
        Route::get('register','MemberController@getRegister')->name('viewRegister');
        Route::post('register','MemberController@register')->name('register');
        Route::get('logout','MemberController@logout')->name('logout');
        Route::get('account','MemberController@getAccount')->name('viewAccount');
        Route::post('account','MemberController@update');
    });
});

// Route::get('father',function(){
//     return view('frontend.layout.father');
// });


Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::group(['namespace' => 'Admin','prefix'=>'admin'], function(){
    Route::get('dashboard','HomeController@index');
    Route::get('profile','UserController@index')->name('show');
    // Route::post('edit/{id}','UserController@update');
    Route::post('profile','UserController@update');
    Route::resource('country', 'CountryController');
    Route::resource('blog', 'BlogController');
    Route::resource('brand','BrandController');
    Route::resource('category','CategoryController');
});

projectBaoVic/app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    public $timestamps = false; 
    protected $fillable = [
    	'name'
    ];
    protected $primaryKey = 'id';
 	protected $table = 'country';
}

projectBaoVic/app/Http/Controllers/Admin/CountryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Country;
use App\Http\Requests\BackEnd\CountryRequest;

class CountryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Country::all();
        return view('admin.country.all',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.country.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CountryRequest $request)
    {
        $insert = new Country;
        $insert->name = $request->name;
        // $insert->description = $request->description;
        $insert->save();
        return redirect()->route('country.index')->with('message','Them country t.cong');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Country::findorfail($id);
        $data->delete();
        // $data->destroy();
        // Country::destroy($id);
        return redirect()->route('country.index')->with('message','Xoa country t.cong');
    }
}

projectBaoVic/resources/views/admin/country/add.blade.php
@extends('admin.layout.father')
@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-5 align-self-center">
            <h4 class="page-title">Basic Table</h4>
        </div>
        <div class="col-7 align-self-center">
            <div class="d-flex align-items-center justify-content-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="#">Home</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Basic Table</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card card-body">
                <h4 class="card-title">Country</h4>
                <h5 class="card-subtitle"> Country </h5>
                <form action="{{route('country.store')}}" method="POST" class="form-horizontal m-t-30">
                    @csrf
                    <div class="form-group">
                        <label><span class="help"> Name </span></label>
                        <input type="text" class="form-control" name="name">
                    </div>
                    @if ($errors->has('name'))
                            <p class="help is-danger" style="color: red">Dien ten</p>
                    @endif
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-success">Add</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

projectBaoVic/resources/views/admin/country/all.blade.php
@extends('admin.layout.father')
@section('content')
<center>
    <div class="col-sm-5">
        @if(session()->has('message'))
        <div class="alert alert-success">
            {!! session()->get('message') !!}
        </div>
        @elseif(session()->has('error'))
        <div class="alert alert-danger">
            {!! session()->get('error') !!}
        </div>
        @endif
    </div>
</center>

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-5 align-self-center">
            <h4 class="page-title">All Country</h4>
        </div>
        <div class="col-7 align-self-center">
            <div class="d-flex align-items-center justify-content-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="#">Home</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">All Country</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">All Country</h4>
                    <h6 class="card-title m-t-40"><i class="m-r-5 font-18 mdi mdi-numeric-1-box-multiple-outline"></i> Table With Outside Padding</h6>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $datas)
                                <tr>
                                    <th scope="row">{{$loop->iteration}}</th>
                                    <td>{{$datas->name}}</td>
                                    <td>
                                        <form action="{{route('country.destroy',$datas->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" onclick="return confirm('Are you sure?')">Xoa</button>
                                        </form>                
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<a href="{{route('country.create')}}">Them Country</a>
@endsection